name: CI

on:
    push:
        branches:
            - master

jobs:
    CI:
        name: Continuous Integration
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3